Update patch set 5
Patch Set 5:

Thanks,

I am actually running msys git from the standard command prompt on Windows 7.  I make sure that all the msys git tools are first in the path.  I use portable git.

I pasted my output at http://pastebin.com/wwmpb7r6

The first error is the spacing (Which you fixed locally), not a big deal

The second error is the Prompt function trying to execute what I write as my username and email.  Most likely because I don't use the same shell as you?  Not sure.  Do you have any idea? Otherwise I can look into it some more.

The third error is :
  File "D:\src\checkout_test\.repo\repo\project.py", line 622, in GetRevisionId
    rev = rem.ToLocal(self.revisionExpr)
  File "D:\src\checkout_test\.repo\repo\git_config.py", line 563, in ToLocal
    raise GitError('remote %s does not have %s' % (self.name, rev))
error.GitError: remote origin does not have refs/heads/master

Is this caused by the missing git links?  Do you have this error too?

The sync seems to be almost fully done though, it does show "Fetching projects: 100% (159/159), done." just above the error.

Thanks

Nicolas

Patch-set: 5