Update patch set 3
Patch Set 3: Code-Review+1 Verified+1

Works as expected.  Since I've made a couple of edits I'll wait for any comments before +2 and submit.


 Fetching project stderr
 ssh: Could not resolve hostname ext: Name or service not known
 fatal: transport 'ext' not allowed
 fatal: transport 'ext' not allowed
 error: Cannot fetch stderr
 
 error: Exited sync due to fetch errors

Patch-set: 3
Reviewer: David Pursehouse <1011123@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=+1