Update patch set 2
Patch Set 2: (2 inline comments)

Conley- Thanks very much for the feedback.

On your test procedure above:

1) I think there needs to be a 'repo start mybr .' before the git add. Correct?

2) Instead of adding "aosp.review=..." in .git/config (which is already there actually), did you mean to change the "merge=..." parameter for the branch created during repo start? By setting mybr.merge=nonexistent, and then running repo upload, I simulate what happens when the user tries to upload to a branch that has been deleted on the server. It is at this point that I git a backtrace from repo:

 $ ~/git-repo/repo upload .
 Traceback (most recent call last):
  File "/home/mkgumbel/git-repo/main.py", line 384, in <module>
    _Main(sys.argv[1:])
  File "/home/mkgumbel/git-repo/main.py", line 364, in _Main
    result = repo._Run(argv) or 0
  File "/home/mkgumbel/git-repo/main.py", line 136, in _Run
    result = cmd.Execute(copts, cargs)
  File "/home/mkgumbel/git-repo/subcmds/upload.py", line 377, in Execute
    avail = project.GetUploadableBranches(branch)
  File "/home/mkgumbel/git-repo/project.py", line 840, in GetUploadableBranches
    rb = self.GetUploadableBranch(branch)
  File "/home/mkgumbel/git-repo/project.py", line 852, in GetUploadableBranch
    if rb.commits:
  File "/home/mkgumbel/git-repo/project.py", line 130, in commits
    '--')
  File "/home/mkgumbel/git-repo/project.py", line 1928, in rev_list
    p.stderr))
 error.GitError: platform/packages/apps/Mms rev-list ('--abbrev=8', '--abbrev-commit', '--pretty=oneline', '--reverse', '--date-order', '^refs/remotes/aosp/nonexistant',  u'refs/heads/mybr', '--'): fatal: bad revision '^refs/remotes/aosp/nonexistant'

Because it fails at this point, it never tries to upload the change and never detects the closed Change-Id.

So, I propose that I catch this error and print a message to the user that they are trying to upload to a branch that no longer exists on the server.

Is this acceptable?

Patch-set: 2
Reviewer: Matthew Gumbel <1010987@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=0