Update patch set 6
Patch Set 6:

This change causes following failure when I run 'repo sync'



Traceback (most recent call last):
  File "/usr/local/google/home/anatol/sources/android-clean/.repo/repo/main.py", line 39, in <module>
    from subcmds.version import Version
  File "/usr/local/google/home/anatol/sources/repo/subcmds/__init__.py", line 36, in <module>
    ['%s' % name])
  File "/usr/local/google/home/anatol/sources/repo/subcmds/init.py", line 166
    if opt.platform == 'auto' and
                                ^
SyntaxError: invalid syntax

Patch-set: 6